name: daily

on:
  schedule:
    - cron: '30 22 * * *'  # UTC 22:30 == KST 07:30
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python digest.py --max-items 8 --out out
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: digest
          path: out/*
